### PR TITLE
Parsing the auth cookie at login is now delegated to the cookie package

### PR DESCRIPTION
**Pull request by hansallis**
I suddenly ran into an issue with this app over the past week or so. Turns out that the first character of the auth cookie got lost in the process, resulting in 403 responses from NewMotion.

Haven't bumped the version yet or anything, just changed the parsing logic.

### CODE REVIEW

**Comment by kaohlive** [comment]
looks good, thanks. i will merge and test it tonight. just ran into probably the same issue, so appreciate the effort a lot

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
From: Hans Allis ***@***.***>
Sent: Thursday, August 19, 2021 4:04:36 PM
To: kaohlive/com.newmotion.my ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [kaohlive/com.newmotion.my] Parsing the auth cookie at login is now delegated to the cookie package (#10)


I suddenly ran into an issue with this app over the past week or so. Turns out that the first character of the auth cookie got lost in the process, resulting in 403 responses from NewMotion.

Haven't bumped the version yet or anything, just changed the parsing logic.

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/kaohlive/com.newmotion.my/pull/10<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkaohlive%2Fcom.newmotion.my%2Fpull%2F10&data=04%7C01%7C%7C3618129f0e884766718808d9631a477b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637649786782036367%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=u9i3ITxBsdSe2EosRFc74NkqWDvHKHJ9oPv7KUYCG0I%3D&reserved=0>

Commit Summary

  *   Parsing the auth cookie at login is now delegated to the cookie package

File Changes

  *   M lib/mnm.js<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkaohlive%2Fcom.newmotion.my%2Fpull%2F10%2Ffiles%23diff-2932f10f178fc7d738940184b206442f60178ef4a33fdda9b35659bd1c2068d0&data=04%7C01%7C%7C3618129f0e884766718808d9631a477b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637649786782046366%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=j6bHqjFsV1pvO%2BF9hc5%2BxAxvf%2FzpcR0r4HqNxb6hBF4%3D&reserved=0> (15)
  *   M package-lock.json<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkaohlive%2Fcom.newmotion.my%2Fpull%2F10%2Ffiles%23diff-053150b640a7ce75eff69d1a22cae7f0f94ad64ce9a855db544dda0929316519&data=04%7C01%7C%7C3618129f0e884766718808d9631a477b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637649786782056355%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=CjFbrJYjYJceX%2BrezAyyktIlPvf2Gg652D5CQp%2FAaRM%3D&reserved=0> (5)
  *   M package.json<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkaohlive%2Fcom.newmotion.my%2Fpull%2F10%2Ffiles%23diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519&data=04%7C01%7C%7C3618129f0e884766718808d9631a477b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637649786782056355%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=aNn1YABQ8Qmsca9Xq%2Fc%2FtWNnnpk4UzwtXtGEQpKVb5A%3D&reserved=0> (2)

Patch Links:

  *   https://github.com/kaohlive/com.newmotion.my/pull/10.patch<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkaohlive%2Fcom.newmotion.my%2Fpull%2F10.patch&data=04%7C01%7C%7C3618129f0e884766718808d9631a477b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637649786782066349%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=vkq9P%2BBjryP9YJCTSVT1dQqNBt%2BwSo7ofp0hD6uK51Y%3D&reserved=0>
  *   https://github.com/kaohlive/com.newmotion.my/pull/10.diff<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkaohlive%2Fcom.newmotion.my%2Fpull%2F10.diff&data=04%7C01%7C%7C3618129f0e884766718808d9631a477b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637649786782066349%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=mHM8LmBcJJ3LaA%2FPQjbuNHcCcE4BEwPtGqR8OT9gFBU%3D&reserved=0>

**Comment by kaohlive** [comment]
Tested and released, thanks for fixing and upgrading. The code is a bit a mess, so any upgrade is appreciated.

**Comment by hansallis** [comment]
Glad I'm able to contribute. I've also got a change in my fork that makes the actual active charge card number available as a tag. I'm using that to inform (known) guest users when their car's fully charged. I'm not sufficiently familiar with the code, so haven't made a PR for that. If it's interesting to you, it's at https://github.com/hansallis/com.newmotion.my/commit/253c9f3b2d3e6f3468c5d4c1f7331cd24995f563

**Comment by kaohlive** [comment]
Is that not covered by the Charge session completed trigger card?
Thats a app level card that has the tags 'connected car' and 'active card' just for cases like this.

**Comment by hansallis** [comment]
As far as I could tell, that information was only being loaded from Device::getStoreValue() and it got stored there during the device setup. My charger's set to public and is often times activated by scanning an rfid card, so I have to read the actual card from the API.

**Comment by kaohlive** [comment]
you are right, i store that value at setup or if a session is started using the flow action. very nice that you take it from the api. very nice addition, i would be happy to merge it

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Pull request merged**
